In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_columns = 20
pd.options.display.max_rows = 20
pd.options.display.max_colwidth = 80
np.set_printoptions(precision=4, suppress=True)

In [2]:
rng = np.random.default_rng(seed=12345)

In [3]:
np.ones((10, 5)).shape

(10, 5)

In [4]:
np.ones((3, 4, 5), dtype=np.float64).strides

(160, 40, 8)

In [5]:
ints = np.ones(10, dtype=np.uint16)
floats = np.ones(10, dtype=np.float32)
np.issubdtype(ints.dtype, np.integer)
np.issubdtype(floats.dtype, np.floating)

In [6]:
np.float64.mro()

In [7]:
np.issubdtype(ints.dtype, np.number)

In [5]:
arr = np.arange(8)
arr
arr.reshape((4, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [6]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [7]:
arr = np.arange(15)
arr.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [8]:
other_arr = np.ones((3, 5))
other_arr.shape
arr.reshape(other_arr.shape)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [9]:
arr = np.arange(15).reshape((5, 3))
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [13]:
arr.ravel(), arr.ravel('F')

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),
 array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11]))

In [15]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [17]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [19]:
np.vstack((arr1, arr2))


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [18]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [20]:
arr = rng.standard_normal((5, 2))
arr

array([[-1.4238,  1.2637],
       [-0.8707, -0.2592],
       [-0.0753, -0.7409],
       [-1.3678,  0.6489],
       [ 0.3611, -1.9529]])

In [21]:
first, second, third = np.split(arr, [1, 3])
second

array([[-0.8707, -0.2592],
       [-0.0753, -0.7409]])

In [22]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = rng.standard_normal((3, 2))


In [25]:
np.r_

array([[ 0.    ,  1.    ,  2.3474,  0.9685],
       [ 2.    ,  3.    , -0.7594,  0.9022],
       [ 4.    ,  5.    , -0.467 , -0.0607]])

In [26]:
np.c_[np.r_[arr1, arr2], arr]

array([[ 0.    ,  1.    ,  0.    ],
       [ 2.    ,  3.    ,  1.    ],
       [ 4.    ,  5.    ,  2.    ],
       [ 2.3474,  0.9685,  3.    ],
       [-0.7594,  0.9022,  4.    ],
       [-0.467 , -0.0607,  5.    ]])

In [29]:
np.c_[1:6, -10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [30]:
arr = np.arange(3)

arr, arr.repeat(3)

(array([0, 1, 2]), array([0, 0, 0, 1, 1, 1, 2, 2, 2]))

In [31]:
arr.repeat([2, 3, 4])

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

In [32]:
arr = rng.standard_normal((2, 2))
arr
arr.repeat(2, axis=0)

array([[ 0.7888, -1.2567],
       [ 0.7888, -1.2567],
       [ 0.5759,  1.399 ],
       [ 0.5759,  1.399 ]])

In [34]:
arr.repeat([2, 3], axis=0)


array([[ 0.7888, -1.2567],
       [ 0.7888, -1.2567],
       [ 0.5759,  1.399 ],
       [ 0.5759,  1.399 ],
       [ 0.5759,  1.399 ]])

In [35]:
arr.repeat([2, 3], axis=1)

array([[ 0.7888,  0.7888, -1.2567, -1.2567, -1.2567],
       [ 0.5759,  0.5759,  1.399 ,  1.399 ,  1.399 ]])

In [36]:
np.tile(arr, 2)

array([[ 0.7888, -1.2567,  0.7888, -1.2567],
       [ 0.5759,  1.399 ,  0.5759,  1.399 ]])

In [37]:
np.tile(arr, (2, 1))

array([[ 0.7888, -1.2567],
       [ 0.5759,  1.399 ],
       [ 0.7888, -1.2567],
       [ 0.5759,  1.399 ]])

In [38]:
np.tile(arr, (3, 2))

array([[ 0.7888, -1.2567,  0.7888, -1.2567],
       [ 0.5759,  1.399 ,  0.5759,  1.399 ],
       [ 0.7888, -1.2567,  0.7888, -1.2567],
       [ 0.5759,  1.399 ,  0.5759,  1.399 ],
       [ 0.7888, -1.2567,  0.7888, -1.2567],
       [ 0.5759,  1.399 ,  0.5759,  1.399 ]])

In [39]:
arr = np.arange(10) * 100
inds = [7, 1, 2, 6]
arr[inds]

array([700, 100, 200, 600])

In [40]:
arr.take(inds)

array([700, 100, 200, 600])

In [41]:
arr.put(inds, 42)
arr

array([  0,  42,  42, 300, 400, 500,  42,  42, 800, 900])

In [42]:
arr.put(inds, [40, 41, 42, 43])
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

In [43]:
inds = [2, 0, 2, 1]
arr = rng.standard_normal((2, 4))
arr

array([[ 1.3223, -0.2997,  0.9029, -1.6216],
       [-0.1582,  0.4495, -1.3436, -0.0817]])

In [46]:
arr.take(inds, axis=1)

array([[ 0.9029,  1.3223,  0.9029, -0.2997],
       [-1.3436, -0.1582, -1.3436,  0.4495]])

In [47]:
arr = np.arange(5)
arr
arr * 4

array([ 0,  4,  8, 12, 16])

In [59]:
arr = rng.standard_normal((4, 3))
arr

array([[ 0.3129, -0.1308,  1.27  ],
       [-0.093 , -0.0662, -1.1082],
       [ 0.136 ,  1.3471,  0.0611],
       [ 0.0709,  0.4337,  0.2775]])

In [60]:
arr.mean(axis=0)

array([0.1067, 0.3959, 0.1251])

In [63]:
demeaned = arr - arr.mean(0)
demeaned

array([[ 0.2062, -0.5268,  1.1449],
       [-0.1997, -0.4621, -1.2333],
       [ 0.0293,  0.9511, -0.064 ],
       [-0.0358,  0.0377,  0.1524]])

In [52]:
demeaned.mean(0)

array([ 0., -0.,  0.])

In [53]:
row_means = arr.mean(1)
row_means.shape

(4,)

In [55]:

# row_means.reshape((4, 1))
demeaned = arr - row_means.reshape((4, 1))
demeaned.mean(1)

array([-0.,  0.,  0.,  0.])

In [56]:
arr - arr.mean(1)

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [57]:
arr - arr.mean(1).reshape((4, 1))

array([[ 0.018 ,  0.9114, -0.9294],
       [ 1.2752, -0.5124, -0.7628],
       [-1.3727,  0.5811,  0.7915],
       [-0.1155, -0.6854,  0.8009]])

In [64]:
arr = np.zeros((4, 4))
arr_3d = arr[:, np.newaxis, :]
arr_3d.shape


(4, 1, 4)

In [66]:
arr_1d = rng.standard_normal(3)
arr_1d[:, np.newaxis], arr_1d[np.newaxis, :]

(array([[0.5303],
        [0.5367],
        [0.6184]]),
 array([[0.5303, 0.5367, 0.6184]]))

In [67]:
arr = rng.standard_normal((3, 4, 5))
depth_means = arr.mean(2)
depth_means

array([[-0.6185, -0.311 , -0.4123, -0.5054],
       [ 0.1388, -0.4948,  0.3935,  0.5167],
       [-0.3551, -0.3214, -0.2838,  0.9712]])

In [68]:
depth_means.shape
demeaned = arr - depth_means[:, :, np.newaxis]
demeaned.mean(2)

array([[ 0.,  0., -0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [-0., -0., -0.,  0.]])

In [69]:
arr = np.zeros((4, 3))
arr[:] = 5
arr

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [70]:
col = np.array([1.28, -0.42, 0.44, 1.6])


In [71]:
arr[:] = col[:, np.newaxis]
arr

array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

In [72]:
arr[:2] = [[-1.37], [0.509]]
arr

array([[-1.37 , -1.37 , -1.37 ],
       [ 0.509,  0.509,  0.509],
       [ 0.44 ,  0.44 ,  0.44 ],
       [ 1.6  ,  1.6  ,  1.6  ]])

In [75]:
from functools import reduce
from operator import __add__, __sub__


reduce(__add__, range(11))

55

In [76]:
arr = np.arange(11)
np.add.reduce(arr)
arr.sum()

55

In [77]:
my_rng = np.random.default_rng(12346)  # for reproducibility
arr = my_rng.standard_normal((5, 5))
arr
arr[::2].sort(1) # sort a few rows
arr[:, :-1] < arr[:, 1:]
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)

array([ True, False,  True, False,  True])

In [78]:
arr = np.arange(15).reshape((3, 5))
np.add.accumulate(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [79]:
np.cumsum(arr, axis=1)

array([[ 0,  1,  3,  6, 10],
       [ 5, 11, 18, 26, 35],
       [10, 21, 33, 46, 60]])

In [80]:
arr = np.arange(3).repeat([1, 2, 2])
arr
np.multiply.outer(arr, np.arange(5))

array([[0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 2, 4, 6, 8]])

In [81]:
x, y = rng.standard_normal((3, 4)), rng.standard_normal(5)
result = np.subtract.outer(x, y)
result.shape

(3, 4, 5)

In [43]:
arr = np.arange(10)
np.add.reduceat(arr, [0, 5, 8])

In [44]:
arr = np.multiply.outer(np.arange(4), np.arange(5))
arr
np.add.reduceat(arr, [0, 2, 4], axis=1)

In [45]:
def add_elements(x, y):
    return x + y
add_them = np.frompyfunc(add_elements, 2, 1)
add_them(np.arange(8), np.arange(8))

In [46]:
add_them = np.vectorize(add_elements, otypes=[np.float64])
add_them(np.arange(8), np.arange(8))

In [47]:
arr = rng.standard_normal(10000)
%timeit add_them(arr, arr)
%timeit np.add(arr, arr)

In [48]:
dtype = [('x', np.float64), ('y', np.int32)]
sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
sarr

In [49]:
sarr[0]
sarr[0]['y']

In [50]:
sarr['x']

In [51]:
dtype = [('x', np.int64, 3), ('y', np.int32)]
arr = np.zeros(4, dtype=dtype)
arr

In [52]:
arr[0]['x']

In [53]:
arr['x']

In [54]:
dtype = [('x', [('a', 'f8'), ('b', 'f4')]), ('y', np.int32)]
data = np.array([((1, 2), 5), ((3, 4), 6)], dtype=dtype)
data['x']
data['y']
data['x']['a']

In [82]:
arr = rng.standard_normal(6)
arr.sort()
arr

array([-1.5382, -0.6236, -0.2529, -0.1585,  0.2821,  1.6151])

In [83]:
arr = rng.standard_normal((3, 5))
arr
arr[:, 0].sort()  # Sort first column values in place
arr

array([[-1.4195,  0.8412, -0.7759,  0.4107, -2.7224],
       [-0.6733,  1.2462,  0.7902,  0.1753, -0.0293],
       [ 1.1218, -1.36  ,  0.2234,  1.7618, -2.1709]])

In [84]:
arr = rng.standard_normal(5)
arr
np.sort(arr)
arr

array([ 0.6285,  0.6012,  0.9508, -0.8692, -0.529 ])

In [85]:
arr = rng.standard_normal((3, 5))
arr
arr.sort(axis=1)
arr

array([[-1.2293, -1.0276, -0.8834, -0.0709,  0.0457],
       [-0.7208, -0.6839, -0.0246,  0.0773,  0.3741],
       [-0.0824, -0.0548,  0.936 ,  1.1206,  1.2385]])

In [86]:
arr[:, ::-1]

array([[ 0.0457, -0.0709, -0.8834, -1.0276, -1.2293],
       [ 0.3741,  0.0773, -0.0246, -0.6839, -0.7208],
       [ 1.2385,  1.1206,  0.936 , -0.0548, -0.0824]])

In [93]:
values = np.array([5, 0, 1, 3, 2])
indexer = np.argsort(values)
indexer

array([1, 2, 4, 3, 0])

In [95]:
values[indexer], values.take(indexer)

(array([0, 1, 2, 3, 5]), array([0, 1, 2, 3, 5]))

In [96]:
arr = rng.standard_normal((3, 5))
arr[0] = values
arr
arr[:, arr[0].argsort()]

array([[ 0.    ,  1.    ,  2.    ,  3.    ,  5.    ],
       [ 0.292 ,  0.6384,  1.3711, -0.0279,  1.3975],
       [ 0.3805,  0.7554,  2.1503, -1.1591, -2.0528]])

In [97]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter = np.lexsort((first_name, last_name))
sorter
list(zip(last_name[sorter], first_name[sorter]))

[('Arnold', 'Jane'),
 ('Arnold', 'Steve'),
 ('Jones', 'Bill'),
 ('Jones', 'Bob'),
 ('Walters', 'Barbara')]

In [98]:
values = np.array(['2:first', '2:second', '1:first', '1:second',
                   '1:third'])
key = np.array([2, 2, 1, 1, 1])
indexer = key.argsort(kind='mergesort')
indexer
values.take(indexer)

array(['1:first', '1:second', '1:third', '2:first', '2:second'],
      dtype='<U8')

In [99]:
rng = np.random.default_rng(12345)
arr = rng.standard_normal(20)
arr
np.partition(arr, 3)

array([-1.9529, -1.4238, -1.3678, -1.2567, -0.8707, -0.7594, -0.7409,
       -0.0607,  0.3611, -0.0753, -0.2592, -0.467 ,  0.5759,  0.9022,
        0.9685,  0.6489,  0.7888,  1.2637,  1.399 ,  2.3474])

In [65]:
indices = np.argpartition(arr, 3)
indices
arr.take(indices)

In [105]:
from bisect import bisect_left

bisect_left([0, 1, 7, 12, 15], 7)

2

In [104]:
arr = np.array([0, 1, 7, 12, 15])
arr.searchsorted(7)

2

In [67]:
arr.searchsorted([0, 8, 11, 16])

In [68]:
arr = np.array([0, 0, 0, 1, 1, 1, 1])
arr.searchsorted([0, 1])
arr.searchsorted([0, 1], side='right')

In [69]:
data = np.floor(rng.uniform(0, 10000, size=50))
bins = np.array([0, 100, 1000, 5000, 10000])
data

In [70]:
labels = bins.searchsorted(data)
labels

In [71]:
pd.Series(data).groupby(labels).mean()

In [72]:
import numpy as np

def mean_distance(x, y):
    nx = len(x)
    result = 0.0
    count = 0
    for i in range(nx):
        result += x[i] - y[i]
        count += 1
    return result / count

In [73]:
mmap = np.memmap('mymmap', dtype='float64', mode='w+',
                 shape=(10000, 10000))
mmap

In [74]:
section = mmap[:5]

In [75]:
section[:] = rng.standard_normal((5, 10000))
mmap.flush()
mmap
del mmap

In [76]:
mmap = np.memmap('mymmap', dtype='float64', shape=(10000, 10000))
mmap

In [77]:
%xdel mmap
!rm mymmap

In [78]:
arr_c = np.ones((100, 10000), order='C')
arr_f = np.ones((100, 10000), order='F')
arr_c.flags
arr_f.flags
arr_f.flags.f_contiguous

In [79]:
%timeit arr_c.sum(1)
%timeit arr_f.sum(1)

In [80]:
arr_f.copy('C').flags

In [81]:
arr_c[:50].flags.contiguous
arr_c[:, :50].flags

In [82]:
%xdel arr_c
%xdel arr_f

In [84]:
pd.options.display.max_rows = PREVIOUS_MAX_ROWS